no password option added

diff --git a/run-over-ssh b/run-over-ssh
--- a/run-over-ssh
+++ b/run-over-ssh
@@ -35,6 +35,7 @@ function print_help {
   echo "   -r, --hostsfile [file]  use the list of hosts from a file (one host per line)"
   echo ""
   echo "   -g, --globalpw          ask one global password for all connections"
+  echo "   -n, --nopw              no password (use ssh directly instead of sshpass)"
   echo "   --sshflags [flags]      set custom ssh flags"
   echo "                           default: '-o ConnectTimeout=5 -o StrictHostKeyChecking=no'"
   echo "   --slogin                make the remote bash act as a login shell"
@@ -69,6 +70,7 @@ log_enabled=""  # -l | --log
 log_file="${script_alias}.log"  # --logfile
 global_pw=""
 passwords=()
+no_pw=""
 ssh_flags="-o ConnectTimeout=5 -o StrictHostKeyChecking=no"   # --sshflags
 s_login=""
 s_interactive=""
@@ -129,12 +131,15 @@ for parameter do
       "-g" | "--globalpw")
         global_pw="true"
         ;;
+      "-n" | "--nopw")
+        no_pw="true"
+        ;;
       "-slogin")
-		s_login="-l"
-		;;
-	  "-sinteractive")
-		s_interactive="-i"
-		;;
+        s_login="-l"
+		    ;;
+	    "-sinteractive")
+		    s_interactive="-i"
+		    ;;
       "-l" | "--log")
         log_enabled="true"
         ;;
@@ -196,6 +201,11 @@ if [ -n "${read_hosts_from_file}" ] && [ ${#hosts[@]} -gt 0 ]; then
   exit 1
 fi
 
+if [ -n "${global_pw}" ] && [ -n "${no_pw}" ]; then
+  echo "Error! Parameter conflict: do not set the 'no password' option when also specifying a global password. Exiting.";
+  exit 1
+fi
+
 # Check file readability (if specified to read from a file)
 
 if [ -n "${read_hosts_from_file}" ] && [ ! -r "${read_hosts_from_file}" ]; then
@@ -224,28 +234,30 @@ if [ -n "${read_hosts_from_file}" ]; then
 fi
 
 
-# Get the SSH passwords
+# Get the SSH passwords (unless 'no password' is set)
 
-if [ -n "${global_pw}" ]; then
-  printf "${username}\'s password (used for all connections): "
-  read -s gpassword
-  echo ""
-  # Fill the passwords array with the global password
-  for host in "${hosts[@]}" 
-  do
-    passwords+=("${gpassword}")
-  done
-else
-  # Ask each password
-  echo "Please set ${username}'s password for each host:"
-  echo ""
-  for host in "${hosts[@]}" 
-  do
-    printf "${username}@${host} password: "
-    read -s host_pw
-    passwords+=("${host_pw}")
+if [ -z "${no_pw}" ]; then
+  if [ -n "${global_pw}" ]; then
+    printf "${username}\'s password (used for all connections): "
+    read -s gpassword
     echo ""
-  done
+    # Fill the passwords array with the global password
+    for host in "${hosts[@]}" 
+    do
+      passwords+=("${gpassword}")
+    done
+  else
+    # Ask each password
+    echo "Please set ${username}'s password for each host:"
+    echo ""
+    for host in "${hosts[@]}" 
+    do
+      printf "${username}@${host} password: "
+      read -s host_pw
+      passwords+=("${host_pw}")
+      echo ""
+    done
+  fi
 fi
 
 echo ""
@@ -260,26 +272,46 @@ if [ -f "${log_file}" ]; then
 fi
 
 # Connect to each host and execute the command/script
-i=0
-for host in "${hosts[@]}" 
-do
-  echo "Connecting as ${username}@${host}..."
-  if [ -n "${read_commands_from_file}" ]; then
-    if [ -n "${quiet_enabled}" ]; then
-      sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -s" < "${read_commands_from_file}" >> "${log_file}"
+if [ -n "${no_pw}" ]; then
+  for host in "${hosts[@]}" 
+  do
+    echo "Connecting as ${username}@${host}..."
+    if [ -n "${read_commands_from_file}" ]; then
+      if [ -n "${quiet_enabled}" ]; then
+        ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -s" < "${read_commands_from_file}" >> "${log_file}"
+      else
+        ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -s" < "${read_commands_from_file}" | tee -a "${log_file}"
+      fi
     else
-      sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -s" < "${read_commands_from_file}" | tee -a "${log_file}"
+      if [ -n "${quiet_enabled}" ]; then
+        ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -c \"${command}\"" >> "${log_file}"
+      else
+        ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -c \"${command}\"" | tee -a "${log_file}"
+      fi
     fi
-  else
-    if [ -n "${quiet_enabled}" ]; then
-      sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -c \"${command}\"" >> "${log_file}"
+  done
+else
+  i=0
+  for host in "${hosts[@]}" 
+  do
+    echo "Connecting as ${username}@${host}..."
+    if [ -n "${read_commands_from_file}" ]; then
+      if [ -n "${quiet_enabled}" ]; then
+        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -s" < "${read_commands_from_file}" >> "${log_file}"
+      else
+        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -s" < "${read_commands_from_file}" | tee -a "${log_file}"
+      fi
     else
-      sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -c \"${command}\"" | tee -a "${log_file}"
+      if [ -n "${quiet_enabled}" ]; then
+        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -c \"${command}\"" >> "${log_file}"
+      else
+        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${s_login} ${s_interactive} -c \"${command}\"" | tee -a "${log_file}"
+      fi
     fi
-  fi
 
-  i=$((i + 1))
-done
+    i=$((i + 1))
+  done
+fi
 
 exit 0
 
