added option to pass arguments to the script file

diff --git a/runoverssh b/runoverssh
--- a/runoverssh
+++ b/runoverssh
@@ -32,6 +32,7 @@ function print_help {
   echo "   -r, --hostsfile [file]     use the list of hosts from a file (one host per line)"
   echo ""
   echo "   -n, --nopw                 no password (use ssh directly instead of sshpass)"
+  echo "   -a, --args                 specify the arguments to be passed to the script file"
   echo "   -l, --log                  save ssh output (default: ${script_alias}.log) (append)"
   echo "   -q, --quiet                disable ssh screen output"
   echo ""
@@ -51,6 +52,8 @@ function print_help {
   echo ""
   echo "  runoverssh --script myscript.sh --hostsfile hostlist remoteuser"
   echo ""
+  echo "  runoverssh --script myscript.sh --args '-q -s -t' --hostsfile hostlist remoteuser"
+  echo ""
   echo "Bugs or Requests: https://github.com/yuriescl/runoverssh/issues"
 }
 
@@ -60,16 +63,17 @@ remote_command=""
 hosts=()
 
 # Optional parameters
-read_commands_from_file=""  # -s | --script
-read_hosts_from_file=""  # -r | --hostsfile
-log_enabled=""  # -l | --log
+read_commands_from_file=""  # -s , --script
+script_arguments="" # -a , --args
+read_hosts_from_file=""  # -r , --hostsfile
+log_enabled=""  # -l , --log
 log_file="${script_alias}.log"  # --logfile
 global_pw=""  # -g, --globalpw
 passwords=()
 no_pw=""  # -n, --nopw
 ssh_flags="-o ConnectTimeout=5 -o StrictHostKeyChecking=no"   # --sshflags
 bash_flags="-l"  # --bashflags
-quiet_enabled="" # -q | --quiet
+quiet_enabled="" # -q , --quiet
 
 if [[ "$1" == "--help" ]]; then
   print_help
@@ -95,6 +99,9 @@ for parameter do
       "-s" | "--script")
         read_commands_from_file="${parameter}"
         ;;
+      "-a" | "--args")
+        script_arguments="${parameter}"
+        ;;
       "-r" | "--hostsfile")
         read_hosts_from_file="${parameter}"
         ;;
@@ -114,7 +121,7 @@ for parameter do
   else  # first or not waiting option
     is_first="no"
     case "${parameter}" in
-      "-s" | "--script" | "-r" | "--hostsfile" | "--logfile" | "--sshflags" | "--bashflags")
+      "-s" | "--script" | "-a" | "--args" | "-r" | "--hostsfile" | "--logfile" | "--sshflags" | "--bashflags")
         waiting_option="${parameter}"
         ;;
       "-g" | "--globalpw")
@@ -172,6 +179,11 @@ if [ -z "${read_commands_from_file}" ] && [ -z "${remote_command}" ] ; then
 fi
 if [ -n "${read_commands_from_file}" ] && [ -n "${remote_command}" ] ; then
   echo "Error: parameter conflict: do not put a command as argument when also specifying a script as parameter. Exiting."
+  exit 1
+fi
+
+if [ -n "${script_arguments}" ] && [ -z "${read_commands_from_file}" ]; then
+  echo "Error: arguments specified but no script file provided. Exiting."
   exit 1
 fi
 
@@ -269,9 +281,9 @@ if [ -n "${no_pw}" ]; then
     echo "Connecting as ${username}@${host}..."
     if [ -n "${read_commands_from_file}" ]; then
       if [ -n "${quiet_enabled}" ]; then
-        ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" >> "${log_file}"
+        ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" "${script_arguments}" >> "${log_file}"
       else
-        ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" | tee -a "${log_file}"
+        ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" "${script_arguments}" | tee -a "${log_file}"
       fi
     else
       if [ -n "${quiet_enabled}" ]; then
@@ -288,9 +300,9 @@ else
     echo "Connecting as ${username}@${host}..."
     if [ -n "${read_commands_from_file}" ]; then
       if [ -n "${quiet_enabled}" ]; then
-        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" >> "${log_file}"
+        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" "${script_arguments}" >> "${log_file}"
       else
-        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" | tee -a "${log_file}"
+        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" "${script_arguments}" | tee -a "${log_file}"
       fi
     else
       if [ -n "${quiet_enabled}" ]; then
