WIP #5: support other shells, POSIX compliance

diff --git a/runoverssh b/runoverssh
--- a/runoverssh
+++ b/runoverssh
@@ -1,6 +1,6 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
-# This program runs a BASH command/script over SSH in a remote host or list of hosts
+# This program runs a shell command/script over SSH in a remote host or list of hosts
 # Copyright (C) 2017  Yuri Escalianti   (https://github.com/yuriescl/runoverssh)
 #
 # This program is free software: you can redistribute it and/or modify
@@ -22,9 +22,9 @@ script_name=`basename "$0"`
 script_alias=`basename -s .sh "$0"`
 
 # Print help
-function print_help {
+print_help() {
   echo "Usage: ${script_name} [OPTIONS] USERNAME COMMAND HOSTS..."
-  echo "Runs a Bash command/script over ssh in one or more hosts."
+  echo "Runs a shell command/script over ssh in one or more hosts."
   echo "Options:"
   echo ""
   echo "   -g, --globalpw             ask one global password for all connections"
@@ -36,10 +36,10 @@ function print_help {
   echo "   -l, --log                  save ssh output (default: ${script_alias}.log) (append)"
   echo "   -q, --quiet                disable ssh screen output"
   echo ""
-  echo "   --bashflags [flags]        set custom bash flags"
-  echo "                               default: '-l'"
+  echo "   --shellflags [flags]       set custom shell flags"
+  echo "                              default (bash): '-l'"
   echo "   --sshflags [flags]         set custom ssh flags"
-  echo "                               default: '-o ConnectTimeout=5 -o StrictHostKeyChecking=no'"
+  echo "                              default: '-o ConnectTimeout=5 -o StrictHostKeyChecking=no'"
   echo "   --logfile [file]           save ssh output to a custom file (append)"
   echo ""
   echo "Examples:"
@@ -60,27 +60,25 @@ function print_help {
 # Standard parameters
 username=""
 remote_command=""
-hosts=()
 
 # Optional parameters
-read_commands_from_file=""  # -s , --script
-script_arguments="" # -a , --args
-read_hosts_from_file=""  # -r , --hostsfile
-log_enabled=""  # -l , --log
-log_file="${script_alias}.log"  # --logfile
-global_pw=""  # -g, --globalpw
-passwords=()
-no_pw=""  # -n, --nopw
-ssh_flags="-o ConnectTimeout=5 -o StrictHostKeyChecking=no"   # --sshflags
-bash_flags="-l"  # --bashflags
-quiet_enabled="" # -q , --quiet
+scriptfile=""  # -s , --script
+args="" # -a , --args
+hostsfile=""  # -r , --hostsfile
+log=""  # -l , --log
+logfile="${script_alias}.log"  # --logfile
+globalpw=""  # -g, --globalpw
+nopw=""  # -n, --nopw
+sshflags="-o ConnectTimeout=5 -o StrictHostKeyChecking=no"   # --sshflags
+shellflags="-l"  # --shellflags
+quiet="" # -q , --quiet
 
-if [[ "$1" == "--help" ]]; then
+if [ "$1" = "--help" ]; then
   print_help
   exit 0
 else
   # Check parameter count
-  if [[ $# -lt 3 ]]; then
+  if [ $# -lt 3 ]; then
     echo "Usage: ${script_name} [OPTIONS] USERNAME COMMAND HOSTS..."
     echo "Use '${script_name} --help' for command help and examples."
     exit 1
@@ -97,23 +95,23 @@ for parameter do
     # Assign the option
     case "${waiting_option}" in
       "-s" | "--script")
-        read_commands_from_file="${parameter}"
+        scriptfile="${parameter}"
         ;;
       "-a" | "--args")
-        script_arguments="${parameter}"
+        args="${parameter}"
         ;;
       "-r" | "--hostsfile")
-        read_hosts_from_file="${parameter}"
+        hostsfile="${parameter}"
         ;;
       "--logfile")
-        log_enabled="true"
-        log_file="${parameter}"
+        log="true"
+        logfile="${parameter}"
         ;;
       "--sshflags")
-        ssh_flags="${parameter}"
+        sshflags="${parameter}"
         ;;
-      "--bashflags")
-        bash_flags="${parameter}"
+      "--shellflags")
+        shellflags="${parameter}"
         ;;
     esac
     waiting_option=""
@@ -121,36 +119,42 @@ for parameter do
   else  # first or not waiting option
     is_first="no"
     case "${parameter}" in
-      "-s" | "--script" | "-a" | "--args" | "-r" | "--hostsfile" | "--logfile" | "--sshflags" | "--bashflags")
+      "-s" | "--script" | "-a" | "--args" | "-r" | "--hostsfile" | "--logfile" | "--sshflags" | "--shellflags")
         waiting_option="${parameter}"
         ;;
       "-g" | "--globalpw")
-        global_pw="true"
+        globalpw="true"
         ;;
       "-n" | "--nopw")
-        no_pw="true"
+        nopw="true"
         ;;
       "-l" | "--log")
-        log_enabled="true"
+        log="true"
         ;;
       "-q" | "--quiet")
-        quiet_enabled="true"
+        quiet="true"
         ;;
       *)
-        if [[ "${parameter}" == "--"* ]] || [[ "${parameter}" == "-"* ]]; then
-          echo "Error: invalid option '${parameter}'. Exiting."
-          exit 1
-        fi
-        
+        case "${$parameter}" in
+          "--"*)
+            echo "Error: invalid option '${parameter}'. Exiting."
+            exit 1 ;;
+          "-"*)
+            echo "Error: invalid option '${parameter}'. Exiting."
+            exit 1 ;;
+          *) ;;
+        esac
+
         # Read the end arguments
         
         if [ -z "${username}" ]; then
           username=${parameter}
         else
-          if [ -z "${read_commands_from_file}" ] && [ -z "${remote_command}" ]; then
+          if [ -z "${scriptfile}" ] && [ -z "${remote_command}" ]; then
             remote_command="${parameter}"
           else
-            if [ -z "${read_hosts_from_file}" ]; then
+            if [ -z "${hostsfile}" ]; then
+                #TODO: stopped here. How to simulate an array in POSIX?
               hosts+=("${parameter}")
             fi # host
           fi #command
@@ -173,119 +177,100 @@ if [ -z "${username}" ]; then
   exit 1
 fi
 
-if [ -z "${read_commands_from_file}" ] && [ -z "${remote_command}" ] ; then
+if [ -z "${scriptfile}" ] && [ -z "${remote_command}" ] ; then
   echo "Error: please specify the command or script file ('-s') to be executed over SSH. Exiting."
   exit 1
 fi
-if [ -n "${read_commands_from_file}" ] && [ -n "${remote_command}" ] ; then
+if [ -n "${scriptfile}" ] && [ -n "${remote_command}" ] ; then
   echo "Error: parameter conflict: do not put a command as argument when also specifying a script as parameter. Exiting."
   exit 1
 fi
 
-if [ -n "${script_arguments}" ] && [ -z "${read_commands_from_file}" ]; then
+if [ -n "${args}" ] && [ -z "${scriptfile}" ]; then
   echo "Error: arguments specified but no script file provided. Exiting."
   exit 1
 fi
 
-if [ -z "${read_hosts_from_file}" ] && [ ${#hosts[@]} -eq 0 ]; then
+if [ -z "${hostsfile}" ] && [ ${#hosts[@]} -eq 0 ]; then
   echo "Error: please specify at least one target host or use the '--hostsfile' option. Exiting."
   exit 1
 fi
-if [ -n "${read_hosts_from_file}" ] && [ ${#hosts[@]} -gt 0 ]; then
+if [ -n "${hostsfile}" ] && [ ${#hosts[@]} -gt 0 ]; then
   echo "Error: parameter conflict: do not list hosts as arguments when also specifying a hostsfile as parameter. Exiting."
   exit 1
 fi
 
-if [ -n "${global_pw}" ] && [ -n "${no_pw}" ]; then
+if [ -n "${globalpw}" ] && [ -n "${nopw}" ]; then
   echo "Error: parameter conflict: do not set the 'no password' option when also specifying a global password. Exiting.";
   exit 1
 fi
 
 # Check file readability (if specified to read from a file)
 
-if [ -n "${read_hosts_from_file}" ] && [ ! -r "${read_hosts_from_file}" ]; then
-	echo "Error: can't read the hosts file '${read_hosts_from_file}'. Exiting."
+if [ -n "${hostsfile}" ] && [ ! -r "${hostsfile}" ]; then
+	echo "Error: can't read the hosts file '${hostsfile}'. Exiting."
 	exit 1
 fi
-if [ -n "${read_commands_from_file}" ] && [ ! -r "${read_commands_from_file}" ]; then
-	echo "Error: can't read the script file '${read_commands_from_file}'. Exiting."
+if [ -n "${scriptfile}" ] && [ ! -r "${scriptfile}" ]; then
+	echo "Error: can't read the script file '${scriptfile}'. Exiting."
   exit 1
 fi
 
 # Check log file
-if [ -d "${log_file}" ]; then
-  echo "Error: log file '${log_file}' is a directory. Exiting."
+if [ -d "${logfile}" ]; then
+  echo "Error: log file '${logfile}' is a directory. Exiting."
   exit 1
 fi
 
 # In case the hostsfile was used, fill the hosts array with them
-if [ -n "${read_hosts_from_file}" ]; then
+if [ -n "${hostsfile}" ]; then
   hosts=()
   while read host; do
     if [ -n "${host}" ]; then
       hosts+=("${host}")
     fi
-  done<"${read_hosts_from_file}"
+  done<"${hostsfile}"
 fi
 
 # Check dependencies
 command -v "ssh" >/dev/null 2>&1 || { echo >&2 "Error: program 'ssh' not found. Exiting."; exit 1; }
 
 # Check for sshpass if the option '-n' is not set
-if [ -z "${no_pw}" ]; then
+if [ -z "${nopw}" ]; then
   command -v "sshpass" >/dev/null 2>&1 || { echo >&2 "Error: program 'sshpass' not found (use the '-n' option to use 'ssh' instead). Exiting."; exit 1; }
 fi
 
 
-# Get the SSH passwords (unless 'no password' is set)
-
-if [ -z "${no_pw}" ]; then
-  if [ -n "${global_pw}" ]; then
+if [ -z "${nopw}" ]; then
+  if [ -n "${globalpw}" ]; then
     printf "${username}\'s password (used for all connections): "
     read -s gpassword
     echo ""
-    # Fill the passwords array with the global password
-    for host in "${hosts[@]}" 
-    do
-      passwords+=("${gpassword}")
-    done
-  else
-    # Ask each password
-    echo "Please set ${username}'s password for each host:"
-    echo ""
-    for host in "${hosts[@]}" 
-    do
-      printf "${username}@${host} password: "
-      read -s host_pw
-      passwords+=("${host_pw}")
-      echo ""
-    done
   fi
 fi
 
 echo ""
 
-# Set variables for easy pipes
-if [ -z "${log_enabled}" ]; then
-  log_file="/dev/null"
+if [ -z "${log}" ]; then
+  logfile="/dev/null"
 fi
 
 # Connect to each host and execute the command/script
-if [ -n "${no_pw}" ]; then
+if [ -n "${nopw}" ]; then
   for host in "${hosts[@]}" 
   do
     echo "Connecting as ${username}@${host}..."
-    if [ -n "${read_commands_from_file}" ]; then
-      if [ -n "${quiet_enabled}" ]; then
-        ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" "${script_arguments}" >> "${log_file}"
+    if [ -n "${scriptfile}" ]; then
+      if [ -n "${quiet}" ]; then
+        ssh ${sshflags} ${username}@${host} "bash ${shellflags} -s" < "${scriptfile}" "${args}" >> "${logfile}"
       else
-        ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" "${script_arguments}" | tee -a "${log_file}"
+        ssh ${sshflags} ${username}@${host} "bash ${shellflags} -s" < "${scriptfile}" "${args}" | tee -a "${logfile}"
       fi
     else
-      if [ -n "${quiet_enabled}" ]; then
-        ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -c \"${remote_command}\"" >> "${log_file}"
+      if [ -n "${quiet}" ]; then
+        ssh ${sshflags} ${username}@${host} "bash ${shellflags} -c \"${remote_command}\"" >> "${logfile}"
       else
-        ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -c \"${remote_command}\"" | tee -a "${log_file}"
+        ssh ${sshflags} ${username}@${host} "bash ${shellflags} -c \"${remote_command}\"" | tee -a "${logfile}"
       fi
     fi
   done
@@ -294,17 +279,17 @@ else
   for host in "${hosts[@]}" 
   do
     echo "Connecting as ${username}@${host}..."
-    if [ -n "${read_commands_from_file}" ]; then
-      if [ -n "${quiet_enabled}" ]; then
-        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" "${script_arguments}" >> "${log_file}"
+    if [ -n "${scriptfile}" ]; then
+      if [ -n "${quiet}" ]; then
+        sshpass -p "${passwords[$i]}" ssh ${sshflags} ${username}@${host} "bash ${shellflags} -s" < "${scriptfile}" "${args}" >> "${logfile}"
       else
-        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -s" < "${read_commands_from_file}" "${script_arguments}" | tee -a "${log_file}"
+        sshpass -p "${passwords[$i]}" ssh ${sshflags} ${username}@${host} "bash ${shellflags} -s" < "${scriptfile}" "${args}" | tee -a "${logfile}"
       fi
     else
-      if [ -n "${quiet_enabled}" ]; then
-        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -c \"${remote_command}\"" >> "${log_file}"
+      if [ -n "${quiet}" ]; then
+        sshpass -p "${passwords[$i]}" ssh ${sshflags} ${username}@${host} "bash ${shellflags} -c \"${remote_command}\"" >> "${logfile}"
       else
-        sshpass -p "${passwords[$i]}" ssh ${ssh_flags} ${username}@${host} "bash ${bash_flags} -c \"${remote_command}\"" | tee -a "${log_file}"
+        sshpass -p "${passwords[$i]}" ssh ${sshflags} ${username}@${host} "bash ${shellflags} -c \"${remote_command}\"" | tee -a "${logfile}"
       fi
     fi
 
